version: "3.9"

services:
  api:
    build: .
    container_name: credit_risk_api
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=file:/app/mlruns
    volumes:
      - ./mlruns:/app/mlruns
